jQuery(document).ready(function(){
  $('.menu>ul').mouseover(function(){
    $(this).find('.submenu').stop().slideDown(100);
    $('#bgwrap').stop().animate({height:'300px'})
  }).mouseout(function(){
    $(this).find('.submenu').stop().slideUp(100);
    $('#bgwrap').stop().animate({height:'100px'})
  });
});